services:
  traefik:
    image: "traefik:2.11"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  migration:
    image: app
    entrypoint: ""
    command: python manage.py makemigrations && python manage.py migrate --noinput
    volumes:
      - ./hackyeahtutor:/app
    depends_on:
      - db
    environment:
      ALLOWED_HOSTS: '["*"]'
      #DEFAULT_DB_ALIAS: db
      DATABASE_URL: postgres://langflow:langflow@db/app
      POSTGRES_DB: app
      POSTGRES_PASSWORD: langflow
      DATABASE_USER: langflow
      DATABASE_HOST: db
  app:
    image: app
    build:
      context: hackyeahtutor
    volumes:
      - ./hackyeahtutor:/app
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - db
      - traefik
    #entrypoint: ""
    #command: ["sleep", "1d"]
    environment:
      ALLOWED_HOSTS: '["*"]'
      #DEFAULT_DB_ALIAS: db
      DATABASE_URL: postgres://langflow:langflow@db/app
      POSTGRES_DB: app
      POSTGRES_PASSWORD: langflow
      DATABASE_USER: langflow
      DATABASE_HOST: db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.priority=1"
      - "traefik.http.routers.app.rule=Host(`hackyeah.plantjournal.online`)"

  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
    volumes:
      - langflow-data:/app/langflow
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metrics.entrypoints=web"
      - "traefik.http.routers.metrics.priority=1"
      - "traefik.http.routers.metrics.rule=Host(`langflow.plantjournal.online`)"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: app
    volumes:
      - app-postgres:/var/lib/postgresql/data

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  app-postgres:
  langflow-data:
